// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pir5-go/healthworker/model"
)

// DeleteHealthchecksIDReader is a Reader for the DeleteHealthchecksID structure.
type DeleteHealthchecksIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHealthchecksIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteHealthchecksIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteHealthchecksIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteHealthchecksIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteHealthchecksIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteHealthchecksIDNoContent creates a DeleteHealthchecksIDNoContent with default headers values
func NewDeleteHealthchecksIDNoContent() *DeleteHealthchecksIDNoContent {
	return &DeleteHealthchecksIDNoContent{}
}

/*DeleteHealthchecksIDNoContent handles this case with default header values.

No Content
*/
type DeleteHealthchecksIDNoContent struct {
	Payload *model.ModelHealthCheck
}

func (o *DeleteHealthchecksIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /healthchecks/{id}][%d] deleteHealthchecksIdNoContent  %+v", 204, o.Payload)
}

func (o *DeleteHealthchecksIDNoContent) GetPayload() *model.ModelHealthCheck {
	return o.Payload
}

func (o *DeleteHealthchecksIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ModelHealthCheck)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteHealthchecksIDForbidden creates a DeleteHealthchecksIDForbidden with default headers values
func NewDeleteHealthchecksIDForbidden() *DeleteHealthchecksIDForbidden {
	return &DeleteHealthchecksIDForbidden{}
}

/*DeleteHealthchecksIDForbidden handles this case with default header values.

Forbidden
*/
type DeleteHealthchecksIDForbidden struct {
	Payload model.HealthWorkerHTTPError
}

func (o *DeleteHealthchecksIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /healthchecks/{id}][%d] deleteHealthchecksIdForbidden  %+v", 403, o.Payload)
}

func (o *DeleteHealthchecksIDForbidden) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *DeleteHealthchecksIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteHealthchecksIDNotFound creates a DeleteHealthchecksIDNotFound with default headers values
func NewDeleteHealthchecksIDNotFound() *DeleteHealthchecksIDNotFound {
	return &DeleteHealthchecksIDNotFound{}
}

/*DeleteHealthchecksIDNotFound handles this case with default header values.

Not Found
*/
type DeleteHealthchecksIDNotFound struct {
	Payload model.HealthWorkerHTTPError
}

func (o *DeleteHealthchecksIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /healthchecks/{id}][%d] deleteHealthchecksIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteHealthchecksIDNotFound) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *DeleteHealthchecksIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteHealthchecksIDInternalServerError creates a DeleteHealthchecksIDInternalServerError with default headers values
func NewDeleteHealthchecksIDInternalServerError() *DeleteHealthchecksIDInternalServerError {
	return &DeleteHealthchecksIDInternalServerError{}
}

/*DeleteHealthchecksIDInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteHealthchecksIDInternalServerError struct {
	Payload model.HealthWorkerHTTPError
}

func (o *DeleteHealthchecksIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /healthchecks/{id}][%d] deleteHealthchecksIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteHealthchecksIDInternalServerError) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *DeleteHealthchecksIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
