// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRoutingpoliciesIDParams creates a new DeleteRoutingpoliciesIDParams object
// with the default values initialized.
func NewDeleteRoutingpoliciesIDParams() *DeleteRoutingpoliciesIDParams {
	var ()
	return &DeleteRoutingpoliciesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRoutingpoliciesIDParamsWithTimeout creates a new DeleteRoutingpoliciesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRoutingpoliciesIDParamsWithTimeout(timeout time.Duration) *DeleteRoutingpoliciesIDParams {
	var ()
	return &DeleteRoutingpoliciesIDParams{

		timeout: timeout,
	}
}

// NewDeleteRoutingpoliciesIDParamsWithContext creates a new DeleteRoutingpoliciesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRoutingpoliciesIDParamsWithContext(ctx context.Context) *DeleteRoutingpoliciesIDParams {
	var ()
	return &DeleteRoutingpoliciesIDParams{

		Context: ctx,
	}
}

// NewDeleteRoutingpoliciesIDParamsWithHTTPClient creates a new DeleteRoutingpoliciesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRoutingpoliciesIDParamsWithHTTPClient(client *http.Client) *DeleteRoutingpoliciesIDParams {
	var ()
	return &DeleteRoutingpoliciesIDParams{
		HTTPClient: client,
	}
}

/*DeleteRoutingpoliciesIDParams contains all the parameters to send to the API endpoint
for the delete routingpolicies ID operation typically these are written to a http.Request
*/
type DeleteRoutingpoliciesIDParams struct {

	/*ID
	  RoutingPolicy ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete routingpolicies ID params
func (o *DeleteRoutingpoliciesIDParams) WithTimeout(timeout time.Duration) *DeleteRoutingpoliciesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete routingpolicies ID params
func (o *DeleteRoutingpoliciesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete routingpolicies ID params
func (o *DeleteRoutingpoliciesIDParams) WithContext(ctx context.Context) *DeleteRoutingpoliciesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete routingpolicies ID params
func (o *DeleteRoutingpoliciesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete routingpolicies ID params
func (o *DeleteRoutingpoliciesIDParams) WithHTTPClient(client *http.Client) *DeleteRoutingpoliciesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete routingpolicies ID params
func (o *DeleteRoutingpoliciesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete routingpolicies ID params
func (o *DeleteRoutingpoliciesIDParams) WithID(id string) *DeleteRoutingpoliciesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete routingpolicies ID params
func (o *DeleteRoutingpoliciesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRoutingpoliciesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
