// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteHealthchecksIDParams creates a new DeleteHealthchecksIDParams object
// with the default values initialized.
func NewDeleteHealthchecksIDParams() *DeleteHealthchecksIDParams {
	var ()
	return &DeleteHealthchecksIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteHealthchecksIDParamsWithTimeout creates a new DeleteHealthchecksIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteHealthchecksIDParamsWithTimeout(timeout time.Duration) *DeleteHealthchecksIDParams {
	var ()
	return &DeleteHealthchecksIDParams{

		timeout: timeout,
	}
}

// NewDeleteHealthchecksIDParamsWithContext creates a new DeleteHealthchecksIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteHealthchecksIDParamsWithContext(ctx context.Context) *DeleteHealthchecksIDParams {
	var ()
	return &DeleteHealthchecksIDParams{

		Context: ctx,
	}
}

// NewDeleteHealthchecksIDParamsWithHTTPClient creates a new DeleteHealthchecksIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteHealthchecksIDParamsWithHTTPClient(client *http.Client) *DeleteHealthchecksIDParams {
	var ()
	return &DeleteHealthchecksIDParams{
		HTTPClient: client,
	}
}

/*DeleteHealthchecksIDParams contains all the parameters to send to the API endpoint
for the delete healthchecks ID operation typically these are written to a http.Request
*/
type DeleteHealthchecksIDParams struct {

	/*ID
	  HealthCheck ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete healthchecks ID params
func (o *DeleteHealthchecksIDParams) WithTimeout(timeout time.Duration) *DeleteHealthchecksIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete healthchecks ID params
func (o *DeleteHealthchecksIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete healthchecks ID params
func (o *DeleteHealthchecksIDParams) WithContext(ctx context.Context) *DeleteHealthchecksIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete healthchecks ID params
func (o *DeleteHealthchecksIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete healthchecks ID params
func (o *DeleteHealthchecksIDParams) WithHTTPClient(client *http.Client) *DeleteHealthchecksIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete healthchecks ID params
func (o *DeleteHealthchecksIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete healthchecks ID params
func (o *DeleteHealthchecksIDParams) WithID(id string) *DeleteHealthchecksIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete healthchecks ID params
func (o *DeleteHealthchecksIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteHealthchecksIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
