// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pir5-go/healthworker/model"
)

// GetHealthchecksReader is a Reader for the GetHealthchecks structure.
type GetHealthchecksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHealthchecksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHealthchecksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetHealthchecksNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetHealthchecksInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetHealthchecksOK creates a GetHealthchecksOK with default headers values
func NewGetHealthchecksOK() *GetHealthchecksOK {
	return &GetHealthchecksOK{}
}

/*GetHealthchecksOK handles this case with default header values.

OK
*/
type GetHealthchecksOK struct {
	Payload []*model.ModelHealthCheck
}

func (o *GetHealthchecksOK) Error() string {
	return fmt.Sprintf("[GET /healthchecks][%d] getHealthchecksOK  %+v", 200, o.Payload)
}

func (o *GetHealthchecksOK) GetPayload() []*model.ModelHealthCheck {
	return o.Payload
}

func (o *GetHealthchecksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHealthchecksNotFound creates a GetHealthchecksNotFound with default headers values
func NewGetHealthchecksNotFound() *GetHealthchecksNotFound {
	return &GetHealthchecksNotFound{}
}

/*GetHealthchecksNotFound handles this case with default header values.

Not Found
*/
type GetHealthchecksNotFound struct {
	Payload model.HealthWorkerHTTPError
}

func (o *GetHealthchecksNotFound) Error() string {
	return fmt.Sprintf("[GET /healthchecks][%d] getHealthchecksNotFound  %+v", 404, o.Payload)
}

func (o *GetHealthchecksNotFound) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *GetHealthchecksNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHealthchecksInternalServerError creates a GetHealthchecksInternalServerError with default headers values
func NewGetHealthchecksInternalServerError() *GetHealthchecksInternalServerError {
	return &GetHealthchecksInternalServerError{}
}

/*GetHealthchecksInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetHealthchecksInternalServerError struct {
	Payload model.HealthWorkerHTTPError
}

func (o *GetHealthchecksInternalServerError) Error() string {
	return fmt.Sprintf("[GET /healthchecks][%d] getHealthchecksInternalServerError  %+v", 500, o.Payload)
}

func (o *GetHealthchecksInternalServerError) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *GetHealthchecksInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
