// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pir5-go/healthworker/model"
)

// NewPostHealthchecksParams creates a new PostHealthchecksParams object
// with the default values initialized.
func NewPostHealthchecksParams() *PostHealthchecksParams {
	var ()
	return &PostHealthchecksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostHealthchecksParamsWithTimeout creates a new PostHealthchecksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostHealthchecksParamsWithTimeout(timeout time.Duration) *PostHealthchecksParams {
	var ()
	return &PostHealthchecksParams{

		timeout: timeout,
	}
}

// NewPostHealthchecksParamsWithContext creates a new PostHealthchecksParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostHealthchecksParamsWithContext(ctx context.Context) *PostHealthchecksParams {
	var ()
	return &PostHealthchecksParams{

		Context: ctx,
	}
}

// NewPostHealthchecksParamsWithHTTPClient creates a new PostHealthchecksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostHealthchecksParamsWithHTTPClient(client *http.Client) *PostHealthchecksParams {
	var ()
	return &PostHealthchecksParams{
		HTTPClient: client,
	}
}

/*PostHealthchecksParams contains all the parameters to send to the API endpoint
for the post healthchecks operation typically these are written to a http.Request
*/
type PostHealthchecksParams struct {

	/*HealthCheck
	  HealthCheck Object

	*/
	HealthCheck *model.ModelHealthCheck

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post healthchecks params
func (o *PostHealthchecksParams) WithTimeout(timeout time.Duration) *PostHealthchecksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post healthchecks params
func (o *PostHealthchecksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post healthchecks params
func (o *PostHealthchecksParams) WithContext(ctx context.Context) *PostHealthchecksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post healthchecks params
func (o *PostHealthchecksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post healthchecks params
func (o *PostHealthchecksParams) WithHTTPClient(client *http.Client) *PostHealthchecksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post healthchecks params
func (o *PostHealthchecksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHealthCheck adds the healthCheck to the post healthchecks params
func (o *PostHealthchecksParams) WithHealthCheck(healthCheck *model.ModelHealthCheck) *PostHealthchecksParams {
	o.SetHealthCheck(healthCheck)
	return o
}

// SetHealthCheck adds the healthCheck to the post healthchecks params
func (o *PostHealthchecksParams) SetHealthCheck(healthCheck *model.ModelHealthCheck) {
	o.HealthCheck = healthCheck
}

// WriteToRequest writes these params to a swagger request
func (o *PostHealthchecksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.HealthCheck != nil {
		if err := r.SetBodyParam(o.HealthCheck); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
