// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pir5-go/healthworker/model"
)

// PostRoutingpoliciesReader is a Reader for the PostRoutingpolicies structure.
type PostRoutingpoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRoutingpoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostRoutingpoliciesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPostRoutingpoliciesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostRoutingpoliciesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostRoutingpoliciesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRoutingpoliciesCreated creates a PostRoutingpoliciesCreated with default headers values
func NewPostRoutingpoliciesCreated() *PostRoutingpoliciesCreated {
	return &PostRoutingpoliciesCreated{}
}

/*PostRoutingpoliciesCreated handles this case with default header values.

Created
*/
type PostRoutingpoliciesCreated struct {
	Payload *model.ModelRoutingPolicy
}

func (o *PostRoutingpoliciesCreated) Error() string {
	return fmt.Sprintf("[POST /routingpolicies][%d] postRoutingpoliciesCreated  %+v", 201, o.Payload)
}

func (o *PostRoutingpoliciesCreated) GetPayload() *model.ModelRoutingPolicy {
	return o.Payload
}

func (o *PostRoutingpoliciesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ModelRoutingPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRoutingpoliciesForbidden creates a PostRoutingpoliciesForbidden with default headers values
func NewPostRoutingpoliciesForbidden() *PostRoutingpoliciesForbidden {
	return &PostRoutingpoliciesForbidden{}
}

/*PostRoutingpoliciesForbidden handles this case with default header values.

Forbidden
*/
type PostRoutingpoliciesForbidden struct {
	Payload model.HealthWorkerHTTPError
}

func (o *PostRoutingpoliciesForbidden) Error() string {
	return fmt.Sprintf("[POST /routingpolicies][%d] postRoutingpoliciesForbidden  %+v", 403, o.Payload)
}

func (o *PostRoutingpoliciesForbidden) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *PostRoutingpoliciesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRoutingpoliciesNotFound creates a PostRoutingpoliciesNotFound with default headers values
func NewPostRoutingpoliciesNotFound() *PostRoutingpoliciesNotFound {
	return &PostRoutingpoliciesNotFound{}
}

/*PostRoutingpoliciesNotFound handles this case with default header values.

Not Found
*/
type PostRoutingpoliciesNotFound struct {
	Payload model.HealthWorkerHTTPError
}

func (o *PostRoutingpoliciesNotFound) Error() string {
	return fmt.Sprintf("[POST /routingpolicies][%d] postRoutingpoliciesNotFound  %+v", 404, o.Payload)
}

func (o *PostRoutingpoliciesNotFound) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *PostRoutingpoliciesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRoutingpoliciesInternalServerError creates a PostRoutingpoliciesInternalServerError with default headers values
func NewPostRoutingpoliciesInternalServerError() *PostRoutingpoliciesInternalServerError {
	return &PostRoutingpoliciesInternalServerError{}
}

/*PostRoutingpoliciesInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostRoutingpoliciesInternalServerError struct {
	Payload model.HealthWorkerHTTPError
}

func (o *PostRoutingpoliciesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /routingpolicies][%d] postRoutingpoliciesInternalServerError  %+v", 500, o.Payload)
}

func (o *PostRoutingpoliciesInternalServerError) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *PostRoutingpoliciesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
