// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pir5-go/healthworker/model"
)

// PostHealthchecksReader is a Reader for the PostHealthchecks structure.
type PostHealthchecksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostHealthchecksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostHealthchecksCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPostHealthchecksForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostHealthchecksNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostHealthchecksInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostHealthchecksCreated creates a PostHealthchecksCreated with default headers values
func NewPostHealthchecksCreated() *PostHealthchecksCreated {
	return &PostHealthchecksCreated{}
}

/*PostHealthchecksCreated handles this case with default header values.

Created
*/
type PostHealthchecksCreated struct {
	Payload *model.ModelHealthCheck
}

func (o *PostHealthchecksCreated) Error() string {
	return fmt.Sprintf("[POST /healthchecks][%d] postHealthchecksCreated  %+v", 201, o.Payload)
}

func (o *PostHealthchecksCreated) GetPayload() *model.ModelHealthCheck {
	return o.Payload
}

func (o *PostHealthchecksCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ModelHealthCheck)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostHealthchecksForbidden creates a PostHealthchecksForbidden with default headers values
func NewPostHealthchecksForbidden() *PostHealthchecksForbidden {
	return &PostHealthchecksForbidden{}
}

/*PostHealthchecksForbidden handles this case with default header values.

Forbidden
*/
type PostHealthchecksForbidden struct {
	Payload model.HealthWorkerHTTPError
}

func (o *PostHealthchecksForbidden) Error() string {
	return fmt.Sprintf("[POST /healthchecks][%d] postHealthchecksForbidden  %+v", 403, o.Payload)
}

func (o *PostHealthchecksForbidden) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *PostHealthchecksForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostHealthchecksNotFound creates a PostHealthchecksNotFound with default headers values
func NewPostHealthchecksNotFound() *PostHealthchecksNotFound {
	return &PostHealthchecksNotFound{}
}

/*PostHealthchecksNotFound handles this case with default header values.

Not Found
*/
type PostHealthchecksNotFound struct {
	Payload model.HealthWorkerHTTPError
}

func (o *PostHealthchecksNotFound) Error() string {
	return fmt.Sprintf("[POST /healthchecks][%d] postHealthchecksNotFound  %+v", 404, o.Payload)
}

func (o *PostHealthchecksNotFound) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *PostHealthchecksNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostHealthchecksInternalServerError creates a PostHealthchecksInternalServerError with default headers values
func NewPostHealthchecksInternalServerError() *PostHealthchecksInternalServerError {
	return &PostHealthchecksInternalServerError{}
}

/*PostHealthchecksInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostHealthchecksInternalServerError struct {
	Payload model.HealthWorkerHTTPError
}

func (o *PostHealthchecksInternalServerError) Error() string {
	return fmt.Sprintf("[POST /healthchecks][%d] postHealthchecksInternalServerError  %+v", 500, o.Payload)
}

func (o *PostHealthchecksInternalServerError) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *PostHealthchecksInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
