// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pir5-go/healthworker/model"
)

// NewPutRoutingpoliciesIDParams creates a new PutRoutingpoliciesIDParams object
// with the default values initialized.
func NewPutRoutingpoliciesIDParams() *PutRoutingpoliciesIDParams {
	var ()
	return &PutRoutingpoliciesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutRoutingpoliciesIDParamsWithTimeout creates a new PutRoutingpoliciesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutRoutingpoliciesIDParamsWithTimeout(timeout time.Duration) *PutRoutingpoliciesIDParams {
	var ()
	return &PutRoutingpoliciesIDParams{

		timeout: timeout,
	}
}

// NewPutRoutingpoliciesIDParamsWithContext creates a new PutRoutingpoliciesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutRoutingpoliciesIDParamsWithContext(ctx context.Context) *PutRoutingpoliciesIDParams {
	var ()
	return &PutRoutingpoliciesIDParams{

		Context: ctx,
	}
}

// NewPutRoutingpoliciesIDParamsWithHTTPClient creates a new PutRoutingpoliciesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutRoutingpoliciesIDParamsWithHTTPClient(client *http.Client) *PutRoutingpoliciesIDParams {
	var ()
	return &PutRoutingpoliciesIDParams{
		HTTPClient: client,
	}
}

/*PutRoutingpoliciesIDParams contains all the parameters to send to the API endpoint
for the put routingpolicies ID operation typically these are written to a http.Request
*/
type PutRoutingpoliciesIDParams struct {

	/*HealthCheck
	  RoutingPolicy Object

	*/
	HealthCheck *model.ModelRoutingPolicy
	/*ID
	  RoutingPolicy ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put routingpolicies ID params
func (o *PutRoutingpoliciesIDParams) WithTimeout(timeout time.Duration) *PutRoutingpoliciesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put routingpolicies ID params
func (o *PutRoutingpoliciesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put routingpolicies ID params
func (o *PutRoutingpoliciesIDParams) WithContext(ctx context.Context) *PutRoutingpoliciesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put routingpolicies ID params
func (o *PutRoutingpoliciesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put routingpolicies ID params
func (o *PutRoutingpoliciesIDParams) WithHTTPClient(client *http.Client) *PutRoutingpoliciesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put routingpolicies ID params
func (o *PutRoutingpoliciesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHealthCheck adds the healthCheck to the put routingpolicies ID params
func (o *PutRoutingpoliciesIDParams) WithHealthCheck(healthCheck *model.ModelRoutingPolicy) *PutRoutingpoliciesIDParams {
	o.SetHealthCheck(healthCheck)
	return o
}

// SetHealthCheck adds the healthCheck to the put routingpolicies ID params
func (o *PutRoutingpoliciesIDParams) SetHealthCheck(healthCheck *model.ModelRoutingPolicy) {
	o.HealthCheck = healthCheck
}

// WithID adds the id to the put routingpolicies ID params
func (o *PutRoutingpoliciesIDParams) WithID(id string) *PutRoutingpoliciesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put routingpolicies ID params
func (o *PutRoutingpoliciesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutRoutingpoliciesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.HealthCheck != nil {
		if err := r.SetBodyParam(o.HealthCheck); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
