// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pir5-go/healthworker/model"
)

// NewPutHealthchecksIDParams creates a new PutHealthchecksIDParams object
// with the default values initialized.
func NewPutHealthchecksIDParams() *PutHealthchecksIDParams {
	var ()
	return &PutHealthchecksIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutHealthchecksIDParamsWithTimeout creates a new PutHealthchecksIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutHealthchecksIDParamsWithTimeout(timeout time.Duration) *PutHealthchecksIDParams {
	var ()
	return &PutHealthchecksIDParams{

		timeout: timeout,
	}
}

// NewPutHealthchecksIDParamsWithContext creates a new PutHealthchecksIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutHealthchecksIDParamsWithContext(ctx context.Context) *PutHealthchecksIDParams {
	var ()
	return &PutHealthchecksIDParams{

		Context: ctx,
	}
}

// NewPutHealthchecksIDParamsWithHTTPClient creates a new PutHealthchecksIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutHealthchecksIDParamsWithHTTPClient(client *http.Client) *PutHealthchecksIDParams {
	var ()
	return &PutHealthchecksIDParams{
		HTTPClient: client,
	}
}

/*PutHealthchecksIDParams contains all the parameters to send to the API endpoint
for the put healthchecks ID operation typically these are written to a http.Request
*/
type PutHealthchecksIDParams struct {

	/*HealthCheck
	  HealthCheck Object

	*/
	HealthCheck *model.ModelHealthCheck
	/*ID
	  HealthCheck ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put healthchecks ID params
func (o *PutHealthchecksIDParams) WithTimeout(timeout time.Duration) *PutHealthchecksIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put healthchecks ID params
func (o *PutHealthchecksIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put healthchecks ID params
func (o *PutHealthchecksIDParams) WithContext(ctx context.Context) *PutHealthchecksIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put healthchecks ID params
func (o *PutHealthchecksIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put healthchecks ID params
func (o *PutHealthchecksIDParams) WithHTTPClient(client *http.Client) *PutHealthchecksIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put healthchecks ID params
func (o *PutHealthchecksIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHealthCheck adds the healthCheck to the put healthchecks ID params
func (o *PutHealthchecksIDParams) WithHealthCheck(healthCheck *model.ModelHealthCheck) *PutHealthchecksIDParams {
	o.SetHealthCheck(healthCheck)
	return o
}

// SetHealthCheck adds the healthCheck to the put healthchecks ID params
func (o *PutHealthchecksIDParams) SetHealthCheck(healthCheck *model.ModelHealthCheck) {
	o.HealthCheck = healthCheck
}

// WithID adds the id to the put healthchecks ID params
func (o *PutHealthchecksIDParams) WithID(id string) *PutHealthchecksIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put healthchecks ID params
func (o *PutHealthchecksIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutHealthchecksIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.HealthCheck != nil {
		if err := r.SetBodyParam(o.HealthCheck); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
