// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pir5-go/healthworker/model"
)

// PutRoutingpoliciesIDReader is a Reader for the PutRoutingpoliciesID structure.
type PutRoutingpoliciesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutRoutingpoliciesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutRoutingpoliciesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPutRoutingpoliciesIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutRoutingpoliciesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutRoutingpoliciesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutRoutingpoliciesIDOK creates a PutRoutingpoliciesIDOK with default headers values
func NewPutRoutingpoliciesIDOK() *PutRoutingpoliciesIDOK {
	return &PutRoutingpoliciesIDOK{}
}

/*PutRoutingpoliciesIDOK handles this case with default header values.

OK
*/
type PutRoutingpoliciesIDOK struct {
	Payload model.ModelRoutingPolicyModel
}

func (o *PutRoutingpoliciesIDOK) Error() string {
	return fmt.Sprintf("[PUT /routingpolicies/{id}][%d] putRoutingpoliciesIdOK  %+v", 200, o.Payload)
}

func (o *PutRoutingpoliciesIDOK) GetPayload() model.ModelRoutingPolicyModel {
	return o.Payload
}

func (o *PutRoutingpoliciesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutRoutingpoliciesIDForbidden creates a PutRoutingpoliciesIDForbidden with default headers values
func NewPutRoutingpoliciesIDForbidden() *PutRoutingpoliciesIDForbidden {
	return &PutRoutingpoliciesIDForbidden{}
}

/*PutRoutingpoliciesIDForbidden handles this case with default header values.

Forbidden
*/
type PutRoutingpoliciesIDForbidden struct {
	Payload model.HealthWorkerHTTPError
}

func (o *PutRoutingpoliciesIDForbidden) Error() string {
	return fmt.Sprintf("[PUT /routingpolicies/{id}][%d] putRoutingpoliciesIdForbidden  %+v", 403, o.Payload)
}

func (o *PutRoutingpoliciesIDForbidden) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *PutRoutingpoliciesIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutRoutingpoliciesIDNotFound creates a PutRoutingpoliciesIDNotFound with default headers values
func NewPutRoutingpoliciesIDNotFound() *PutRoutingpoliciesIDNotFound {
	return &PutRoutingpoliciesIDNotFound{}
}

/*PutRoutingpoliciesIDNotFound handles this case with default header values.

Not Found
*/
type PutRoutingpoliciesIDNotFound struct {
	Payload model.HealthWorkerHTTPError
}

func (o *PutRoutingpoliciesIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /routingpolicies/{id}][%d] putRoutingpoliciesIdNotFound  %+v", 404, o.Payload)
}

func (o *PutRoutingpoliciesIDNotFound) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *PutRoutingpoliciesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutRoutingpoliciesIDInternalServerError creates a PutRoutingpoliciesIDInternalServerError with default headers values
func NewPutRoutingpoliciesIDInternalServerError() *PutRoutingpoliciesIDInternalServerError {
	return &PutRoutingpoliciesIDInternalServerError{}
}

/*PutRoutingpoliciesIDInternalServerError handles this case with default header values.

Internal Server Error
*/
type PutRoutingpoliciesIDInternalServerError struct {
	Payload model.HealthWorkerHTTPError
}

func (o *PutRoutingpoliciesIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /routingpolicies/{id}][%d] putRoutingpoliciesIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PutRoutingpoliciesIDInternalServerError) GetPayload() model.HealthWorkerHTTPError {
	return o.Payload
}

func (o *PutRoutingpoliciesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
