// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// HealthWorkerHTTPError health worker HTTP error
// swagger:model health_worker.HTTPError
type HealthWorkerHTTPError interface{}
