// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ModelRoutingPolicyModel model routing policy model
// swagger:model model.RoutingPolicyModel
type ModelRoutingPolicyModel interface{}
