// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelRoutingPolicies model routing policies
// swagger:model model.RoutingPolicies
type ModelRoutingPolicies []*ModelRoutingPoliciesItems0

// Validate validates this model routing policies
func (m ModelRoutingPolicies) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ModelRoutingPoliciesItems0 model routing policies items0
// swagger:model ModelRoutingPoliciesItems0
type ModelRoutingPoliciesItems0 struct {

	// db
	Db string `json:"db,omitempty"`

	// health check ID
	HealthCheckID int64 `json:"healthCheckID,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// record ID
	RecordID int64 `json:"recordID,omitempty"`

	// type
	Type int64 `json:"type,omitempty"`
}

// Validate validates this model routing policies items0
func (m *ModelRoutingPoliciesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelRoutingPoliciesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelRoutingPoliciesItems0) UnmarshalBinary(b []byte) error {
	var res ModelRoutingPoliciesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
