// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pdns-api/model"
)

// DeleteDomainsNameReader is a Reader for the DeleteDomainsName structure.
type DeleteDomainsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDomainsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteDomainsNameNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteDomainsNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteDomainsNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteDomainsNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDomainsNameNoContent creates a DeleteDomainsNameNoContent with default headers values
func NewDeleteDomainsNameNoContent() *DeleteDomainsNameNoContent {
	return &DeleteDomainsNameNoContent{}
}

/*DeleteDomainsNameNoContent handles this case with default header values.

No Content
*/
type DeleteDomainsNameNoContent struct {
	Payload *model.ModelDomain
}

func (o *DeleteDomainsNameNoContent) Error() string {
	return fmt.Sprintf("[DELETE /domains/{name}][%d] deleteDomainsNameNoContent  %+v", 204, o.Payload)
}

func (o *DeleteDomainsNameNoContent) GetPayload() *model.ModelDomain {
	return o.Payload
}

func (o *DeleteDomainsNameNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ModelDomain)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDomainsNameForbidden creates a DeleteDomainsNameForbidden with default headers values
func NewDeleteDomainsNameForbidden() *DeleteDomainsNameForbidden {
	return &DeleteDomainsNameForbidden{}
}

/*DeleteDomainsNameForbidden handles this case with default header values.

Forbidden
*/
type DeleteDomainsNameForbidden struct {
	Payload model.PdnsAPIHTTPError
}

func (o *DeleteDomainsNameForbidden) Error() string {
	return fmt.Sprintf("[DELETE /domains/{name}][%d] deleteDomainsNameForbidden  %+v", 403, o.Payload)
}

func (o *DeleteDomainsNameForbidden) GetPayload() model.PdnsAPIHTTPError {
	return o.Payload
}

func (o *DeleteDomainsNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDomainsNameNotFound creates a DeleteDomainsNameNotFound with default headers values
func NewDeleteDomainsNameNotFound() *DeleteDomainsNameNotFound {
	return &DeleteDomainsNameNotFound{}
}

/*DeleteDomainsNameNotFound handles this case with default header values.

Not Found
*/
type DeleteDomainsNameNotFound struct {
	Payload model.PdnsAPIHTTPError
}

func (o *DeleteDomainsNameNotFound) Error() string {
	return fmt.Sprintf("[DELETE /domains/{name}][%d] deleteDomainsNameNotFound  %+v", 404, o.Payload)
}

func (o *DeleteDomainsNameNotFound) GetPayload() model.PdnsAPIHTTPError {
	return o.Payload
}

func (o *DeleteDomainsNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDomainsNameInternalServerError creates a DeleteDomainsNameInternalServerError with default headers values
func NewDeleteDomainsNameInternalServerError() *DeleteDomainsNameInternalServerError {
	return &DeleteDomainsNameInternalServerError{}
}

/*DeleteDomainsNameInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteDomainsNameInternalServerError struct {
	Payload model.PdnsAPIHTTPError
}

func (o *DeleteDomainsNameInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /domains/{name}][%d] deleteDomainsNameInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteDomainsNameInternalServerError) GetPayload() model.PdnsAPIHTTPError {
	return o.Payload
}

func (o *DeleteDomainsNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
