// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pdns-api/model"
)

// GetRecordsReader is a Reader for the GetRecords structure.
type GetRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRecordsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetRecordsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRecordsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRecordsOK creates a GetRecordsOK with default headers values
func NewGetRecordsOK() *GetRecordsOK {
	return &GetRecordsOK{}
}

/*GetRecordsOK handles this case with default header values.

OK
*/
type GetRecordsOK struct {
	Payload []*model.ModelRecord
}

func (o *GetRecordsOK) Error() string {
	return fmt.Sprintf("[GET /records][%d] getRecordsOK  %+v", 200, o.Payload)
}

func (o *GetRecordsOK) GetPayload() []*model.ModelRecord {
	return o.Payload
}

func (o *GetRecordsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRecordsNotFound creates a GetRecordsNotFound with default headers values
func NewGetRecordsNotFound() *GetRecordsNotFound {
	return &GetRecordsNotFound{}
}

/*GetRecordsNotFound handles this case with default header values.

Not Found
*/
type GetRecordsNotFound struct {
	Payload model.PdnsAPIHTTPError
}

func (o *GetRecordsNotFound) Error() string {
	return fmt.Sprintf("[GET /records][%d] getRecordsNotFound  %+v", 404, o.Payload)
}

func (o *GetRecordsNotFound) GetPayload() model.PdnsAPIHTTPError {
	return o.Payload
}

func (o *GetRecordsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRecordsInternalServerError creates a GetRecordsInternalServerError with default headers values
func NewGetRecordsInternalServerError() *GetRecordsInternalServerError {
	return &GetRecordsInternalServerError{}
}

/*GetRecordsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetRecordsInternalServerError struct {
	Payload model.PdnsAPIHTTPError
}

func (o *GetRecordsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /records][%d] getRecordsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRecordsInternalServerError) GetPayload() model.PdnsAPIHTTPError {
	return o.Payload
}

func (o *GetRecordsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
