// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/pir5/pdns-api/models"
)

// NewPostRecordsParams creates a new PostRecordsParams object
// with the default values initialized.
func NewPostRecordsParams() *PostRecordsParams {
	var ()
	return &PostRecordsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRecordsParamsWithTimeout creates a new PostRecordsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRecordsParamsWithTimeout(timeout time.Duration) *PostRecordsParams {
	var ()
	return &PostRecordsParams{

		timeout: timeout,
	}
}

// NewPostRecordsParamsWithContext creates a new PostRecordsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRecordsParamsWithContext(ctx context.Context) *PostRecordsParams {
	var ()
	return &PostRecordsParams{

		Context: ctx,
	}
}

// NewPostRecordsParamsWithHTTPClient creates a new PostRecordsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRecordsParamsWithHTTPClient(client *http.Client) *PostRecordsParams {
	var ()
	return &PostRecordsParams{
		HTTPClient: client,
	}
}

/*PostRecordsParams contains all the parameters to send to the API endpoint
for the post records operation typically these are written to a http.Request
*/
type PostRecordsParams struct {

	/*Record
	  Record Object

	*/
	Record *models.ModelRecord

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post records params
func (o *PostRecordsParams) WithTimeout(timeout time.Duration) *PostRecordsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post records params
func (o *PostRecordsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post records params
func (o *PostRecordsParams) WithContext(ctx context.Context) *PostRecordsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post records params
func (o *PostRecordsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post records params
func (o *PostRecordsParams) WithHTTPClient(client *http.Client) *PostRecordsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post records params
func (o *PostRecordsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRecord adds the record to the post records params
func (o *PostRecordsParams) WithRecord(record *models.ModelRecord) *PostRecordsParams {
	o.SetRecord(record)
	return o
}

// SetRecord adds the record to the post records params
func (o *PostRecordsParams) SetRecord(record *models.ModelRecord) {
	o.Record = record
}

// WriteToRequest writes these params to a swagger request
func (o *PostRecordsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Record != nil {
		if err := r.SetBodyParam(o.Record); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
