// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pdns-api/model"
)

// PostDomainsReader is a Reader for the PostDomains structure.
type PostDomainsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDomainsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostDomainsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPostDomainsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostDomainsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDomainsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostDomainsCreated creates a PostDomainsCreated with default headers values
func NewPostDomainsCreated() *PostDomainsCreated {
	return &PostDomainsCreated{}
}

/*PostDomainsCreated handles this case with default header values.

Created
*/
type PostDomainsCreated struct {
	Payload *model.ModelDomain
}

func (o *PostDomainsCreated) Error() string {
	return fmt.Sprintf("[POST /domains][%d] postDomainsCreated  %+v", 201, o.Payload)
}

func (o *PostDomainsCreated) GetPayload() *model.ModelDomain {
	return o.Payload
}

func (o *PostDomainsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ModelDomain)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDomainsForbidden creates a PostDomainsForbidden with default headers values
func NewPostDomainsForbidden() *PostDomainsForbidden {
	return &PostDomainsForbidden{}
}

/*PostDomainsForbidden handles this case with default header values.

Forbidden
*/
type PostDomainsForbidden struct {
	Payload model.PdnsAPIHTTPError
}

func (o *PostDomainsForbidden) Error() string {
	return fmt.Sprintf("[POST /domains][%d] postDomainsForbidden  %+v", 403, o.Payload)
}

func (o *PostDomainsForbidden) GetPayload() model.PdnsAPIHTTPError {
	return o.Payload
}

func (o *PostDomainsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDomainsNotFound creates a PostDomainsNotFound with default headers values
func NewPostDomainsNotFound() *PostDomainsNotFound {
	return &PostDomainsNotFound{}
}

/*PostDomainsNotFound handles this case with default header values.

Not Found
*/
type PostDomainsNotFound struct {
	Payload model.PdnsAPIHTTPError
}

func (o *PostDomainsNotFound) Error() string {
	return fmt.Sprintf("[POST /domains][%d] postDomainsNotFound  %+v", 404, o.Payload)
}

func (o *PostDomainsNotFound) GetPayload() model.PdnsAPIHTTPError {
	return o.Payload
}

func (o *PostDomainsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDomainsInternalServerError creates a PostDomainsInternalServerError with default headers values
func NewPostDomainsInternalServerError() *PostDomainsInternalServerError {
	return &PostDomainsInternalServerError{}
}

/*PostDomainsInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostDomainsInternalServerError struct {
	Payload model.PdnsAPIHTTPError
}

func (o *PostDomainsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /domains][%d] postDomainsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostDomainsInternalServerError) GetPayload() model.PdnsAPIHTTPError {
	return o.Payload
}

func (o *PostDomainsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
