// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/pir5/pir5-go/dnsapi/model"
)

// NewPutRecordsIDParams creates a new PutRecordsIDParams object
// with the default values initialized.
func NewPutRecordsIDParams() *PutRecordsIDParams {
	var ()
	return &PutRecordsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutRecordsIDParamsWithTimeout creates a new PutRecordsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutRecordsIDParamsWithTimeout(timeout time.Duration) *PutRecordsIDParams {
	var ()
	return &PutRecordsIDParams{

		timeout: timeout,
	}
}

// NewPutRecordsIDParamsWithContext creates a new PutRecordsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutRecordsIDParamsWithContext(ctx context.Context) *PutRecordsIDParams {
	var ()
	return &PutRecordsIDParams{

		Context: ctx,
	}
}

// NewPutRecordsIDParamsWithHTTPClient creates a new PutRecordsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutRecordsIDParamsWithHTTPClient(client *http.Client) *PutRecordsIDParams {
	var ()
	return &PutRecordsIDParams{
		HTTPClient: client,
	}
}

/*PutRecordsIDParams contains all the parameters to send to the API endpoint
for the put records ID operation typically these are written to a http.Request
*/
type PutRecordsIDParams struct {

	/*ID
	  Record ID

	*/
	ID int64
	/*Record
	  Record Object

	*/
	Record *model.ModelRecord

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put records ID params
func (o *PutRecordsIDParams) WithTimeout(timeout time.Duration) *PutRecordsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put records ID params
func (o *PutRecordsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put records ID params
func (o *PutRecordsIDParams) WithContext(ctx context.Context) *PutRecordsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put records ID params
func (o *PutRecordsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put records ID params
func (o *PutRecordsIDParams) WithHTTPClient(client *http.Client) *PutRecordsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put records ID params
func (o *PutRecordsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put records ID params
func (o *PutRecordsIDParams) WithID(id int64) *PutRecordsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put records ID params
func (o *PutRecordsIDParams) SetID(id int64) {
	o.ID = id
}

// WithRecord adds the record to the put records ID params
func (o *PutRecordsIDParams) WithRecord(record *model.ModelRecord) *PutRecordsIDParams {
	o.SetRecord(record)
	return o
}

// SetRecord adds the record to the put records ID params
func (o *PutRecordsIDParams) SetRecord(record *model.ModelRecord) {
	o.Record = record
}

// WriteToRequest writes these params to a swagger request
func (o *PutRecordsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Record != nil {
		if err := r.SetBodyParam(o.Record); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
